- hosts: localhost
  tasks:
    - name: Add firewall rule to allow HTTP traffic
      azure_rm_networksecuritygroup:
        resource_group: "{{ resource_group_name }}"
        name: "example-nsg"
        security_rules:
          - name: "allow_http"
            priority: 1000
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "80"
            source_address_prefix: "*"
            destination_address_prefix: "*"

    - name: Add firewall rule to allow HTTPS traffic
      azure_rm_networksecuritygroup:
        resource_group: "{{ resource_group_name }}"
        name: "example-nsg"
        security_rules:
          - name: "allow_https"
            priority: 1001
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "443"
            source_address_prefix: "*"
            destination_address_prefix: "*"